In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [49]:
# Универ для одного

In [8]:
UC = array([
    [.129, .545],
    [.277, .273],
    [.594, .182]
])

C = array([.17, .83]).reshape((-1, 1))

In [9]:
U = matmul(UC, C)

In [12]:
U

array([[ 0.47428],
       [ 0.27368],
       [ 0.25204]])

In [50]:
# Универ для двоих (не сработало)

In [32]:
UC2 = array([
    [[.129, .545], 
    [.277, .273], 
    [.594, .182]], 
    [[.2, .5],
    [.3, .2],
    [.5, .3]]
])

UC2.shape

(2, 3, 2)

In [33]:
C2C1 = array([
    [.17, .2],
    [.83, .3]
])

In [36]:
C1 = array([.5]*2).reshape((-1, 1))

In [48]:
matmul(matmul(UC2, C2C1), C1).sum(0)

array([[ 0.65129],
       [ 0.37399],
       [ 0.47472]])

In [51]:
# Вычисление весов из матриц

In [52]:
A = array([
    [1, 1/5],
    [5, 1]
])

In [59]:
(A / A.sum(0)).mean(1)

array([ 0.16666667,  0.83333333])

In [63]:
def compute_weights(relative_weights):
    return (relative_weights / relative_weights.sum(0)).mean(1)

In [105]:
class ConsistencyEstimator:
    def __init__(self, relative_weights):
        self.relative_weights = relative_weights
    
    def consistency(self):
        weights = compute_weights(self.relative_weights)
        n_max = matmul(self.relative_weights, weights).sum()
        n = len(weights)
        c_i = (n_max - n) / (n - 1)
        r_i = 1.98 * (n - 2) / n
        c_r = c_i / r_i
        return c_r
        
    def is_consistent(self):
        c_r = self.consistency()
        return c_r < .1
        

In [101]:
AL = array([
    [1, 1/2, 1/5],
    [2, 1, 1/2],
    [5, 2, 1]
])

AR = array([
    [1, 2, 3],
    [1/2, 1, 3/2],
    [1/3, 2/3, 1]
])

In [104]:
compute_weights(AL).reshape((-1, 1))

array([[ 0.1285014 ],
       [ 0.27661064],
       [ 0.59488796]])

In [91]:
matmul(AL, compute_weights(AL))

array([ 0.38578431,  0.83105742,  1.79061625])

In [92]:
matmul(AL, compute_weights(AL).reshape((-1, 1)))

array([[ 0.38578431],
       [ 0.83105742],
       [ 1.79061625]])

In [108]:
ConsistencyEstimator(AL).consistency()

0.0056499872676341375

# Задача 

A new author sets three criteria for selecting a publisher for his textbook: royalty- percentage (R), marketing (M), and advance payment (A). Two publishers, H and P. have expressed interest in the book. Using the following comparison matrices, rank the two publishers and assess the consistency of the decision.

In [134]:
A = array([
    [1, 1, 1/4],
    [1, 1, 1/5],
    [4, 5, 1]
])

AR = array([
    [1, 2],
    [1/2, 1]
])

AM = array([
    [1, 1/2],
    [2, 1]
])

AA = ones((2, 2))

In [135]:
ConsistencyEstimator(A).is_consistent()

True

In [136]:
for mx in [A, AR, AM, AA]:
    print(compute_weights(mx))

[ 0.16064587  0.14915161  0.69020252]
[ 0.66666667  0.33333333]
[ 0.33333333  0.66666667]
[ 0.5  0.5]


In [131]:
W1 = array([compute_weights(mx) for mx in [AR, AM, AA]]).T
W2 = compute_weights(A)

In [132]:
matmul(W1, W2)

array([ 0.50191571,  0.49808429])

Выбрать следует издателя H